---

- set_fact:
    file_path: "/tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/connect_hostpool/inputs/hostpool_url"
  when: hostpool_url is defined
- set_fact:
    file_dir: "{{ file_path | dirname }}"
  when: hostpool_url is defined

- name: "Ensure directory <{{ file_dir }}> exists"
  file:
    path: "{{ file_dir }}"
    state: directory
  when: hostpool_url is defined

- name: "Echo <{{ hostpool_url }}> into {{ file_path }}"
  shell: "echo '{{ hostpool_url }}' > {{ file_path }}"
  when: hostpool_url is defined
