{
"ALIEN_DIST_URL": "http://54.246.249.105/dist/2.1.0-SM5/alien4cloud-artemis-dist-2.1.0-SM5-dist.tar.gz",
"CONSUL_DIST_URL": "https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip",
"YORC_DIST_URL": "https://github.com/ystia/yorc/releases/download/v3.0.0/yorc-server-3.0.0-distrib.zip",
"TERRAFORM_DIST_URL": "https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip",
"AWS_ACCESS_KEY": "",
"AWS_SECRET_KEY": "",
"AWS_REGION": "eu-west-1",
"a4c_protocol": "http",
"a4c_ip": "34.245.10.8",
"a4c_port": 8088,
"a4c_admin_usr": "admin",
"a4c_admin_pwd": "4dm1n",
"discriminator": "ART_YORK_",
"ssl_keystore_source_location": "/var/folders/2d/3krvvvn538ggxjx8mtvwmj_c0000gn/T/tmp.vaCqIRYH/server-keystore.p12",
"ssl_src_keystore_password": "changeIt!",
"ssl_dest_keystore_password": "changeIt!",
"ssl_key_password": "changeIt!",

"EOF": "" }
